name: "Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Acquire uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Sync uv
      run: uv sync --dev
    - name: Run tests
      run: uv run coverage run -m pytest
    - name: Coverage report
      run: uv run coverage report
